name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          2.7,
          3.5,
          3.6,
          3.7,
          3.8,
          3.9,
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14",
          latest,
          rc
        ]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: pip install -r requirements.txt
        if: matrix.python-version != '2.7'
      - run: pip install -r requirements.py2.txt
        if: matrix.python-version == '2.7'
      - run: |
          pip install black
          black . --check
        if: matrix.python-version == '3.14'
      - run: python setup.py test
        env:
          HTTPBIN: httpbin.bemisc.com
          PLUGIN_PATH: ./*/src;./*/*src
  build-pypy:
    name: Build PyPy
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          2.7,
          #3.6,
          #3.7,
          #3.8,
          #3.9,
          #"3.10"
        ]
    runs-on: ubuntu-latest
    container: pypy:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: pypy --version
      - run: pip install -r requirements.txt
        if: matrix.python-version != '2.7'
      - run: pip install -r requirements.py2.txt
        if: matrix.python-version == '2.7'
      - run: |
          pip install black
          black . --check
        if: matrix.python-version == '3.14'
      - run: pypy setup.py test
        env:
          HTTPBIN: httpbin.bemisc.com
          PLUGIN_PATH: ./*/src;./*/*src
  build-arm:
    name: Build ARM
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          "3.9",
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14",
          latest
        ]
    runs-on: ubuntu-24.04-arm
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: pip install -r requirements.txt
      - run: python setup.py test
        env:
          HTTPBIN: httpbin.bemisc.com
          PLUGIN_PATH: ./*/src;./*/*src
  build-pypy-arm:
    name: Build PyPy ARM
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          "2.7",
          #3.6,
          #3.7,
          #3.8,
          #3.9,
          #"3.10"
        ]
    runs-on: ubuntu-24.04-arm
    container: pypy:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: pypy --version
      - run: pip install -r requirements.txt
      - run: pypy setup.py test
        env:
          HTTPBIN: httpbin.bemisc.com
          PLUGIN_PATH: ./*/src;./*/*src
